name: build and unittest
on:
  pull_request:
    branches:
      - master
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    strategy:
      fail-fast: false
      matrix:
        compiler:
          - gcc
          - clang

    container:
      image: schnitzeltony/fedora-qt5:32
    steps:
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          repo: ZeraGmbH/zera-metaproject
          name: buildroot
          workflow: buildAndExportArtifact.yml
          path: /github/home/install/
      - uses: actions/checkout@master
        with:
          submodules: recursive
      - name: install deps
        run: |
          sudo dnf -y install xorg-x11-server-Xvfb
      - name: Build
        run: |
          echo $HOME
          echo $GITHUB_WORKSPACE
          cd $HOME
          mkdir -p "$HOME/targetbuild"
          cd "$HOME/targetbuild"

          if [ "${{ matrix.compiler }}" == "clang" ]; then
            export CC=clang
            export CXX=clang++
          fi

          cmake $GITHUB_WORKSPACE \
           -DCMAKE_PREFIX_PATH="$HOME/install/usr;/usr" \
           -DCMAKE_INSTALL_PREFIX:PATH="$HOME/install/usr" \
           -DCMAKE_INSTALL_SYSCONFDIR="$HOME/install/etc"
          # compile / install
           make -j $(getconf _NPROCESSORS_ONLN)
      - name: unittest
        run: |
          export DISPLAY=:99
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
          cd "$HOME/targetbuild"
          ctest -V
